### ISSUE TITLE
Segfault in cleanup method in testing

### ISSUE THREAD

**Issue by sg126** [DTxCode/SWDev-A1-Part2#12]
We're receiving a segmentation fault when cleanup() is run. We believe the issue is with the line `delete s_vals[i];` since it runs fine when that line is commented out. Any suggestions as to what may be occurring here?

**Comment by DTxCode** [comment]
Hey guys, since the test 'news' all of the s_vals it expects to be responsible for 'deleting' them too. Maybe you're deleting the string accidently inside your map? 

This is a debatable design principle but in general if your map is given an object allocated on the heap it shouldn't be deleting it because presumably someone else will (in this case the test file).

Let me know if that helps.

**Comment by sg126** [comment]
Yes it does! Thank you for your help on this.
