### ISSUE TITLE
Use common string.h and object.h

### ISSUE THREAD

**Issue by MHebes** [DTxCode/SWDev-A1-Part2#8]
Based on piazza, and to keep things consistent with the other repos, I recommend we use a consistent object.h and string.h interface with the rest of the class.

https://github.com/chasebish/cwc_object_string

Let me know what you think. Tests will need to be updated as well.

**Comment by DTxCode** [comment]
Hey guys, based on https://piazza.com/class/k51bluky59n2jr?cid=314 we think you're allowed to change string.h and object.h to whatever you like. I took a look at our tests and I think if you changed yours to the ones on piazza/in that github it should still pass our spec. Let us know if you think otherwise.
